<?php
/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function geoserver_help($path, $arg) {
  switch ($path) {
    case "admin/help#geoserver":
      return t("Displays links to nodes created on this date");
      break;
  }
}

function geoserver_menu() {
  $items = [];

  $items["admin/geoserver/settings"] = [
    "title" => "Geoserver Admin",
    "description" => "Provides a form so users can manage the settings",
    "page callback" => "geoserver_admin_list",
    "page arguments" => [],
    "access arguments" => ["use geoserver"],
    "file" => "includes/geoserver.admin.inc",
  ];

  // Add geoserver credentials
  $items["admin/geoserver/settings/credentials/add"] = [
    "title" => "Add Geoserver Credentials",
    "description" => "Allow users to add geoserver credentials",
    "page callback" => "drupal_get_form",
    "page arguments" => [
      "geoserver_admin_settings_credentials_form",
      "add"
    ],
    "access arguments" => ["administer geoserver"],
    "file" => "includes/geoserver.admin.inc",
  ];

  // Edit geoserver credentials.
  $items["admin/geoserver/settings/credentials/edit"] = [
    "title" => "Edit Credentials",
    "description" => "Edit an existing credentials.",
    "page callback" => "drupal_get_form",
    "page arguments" => [
      "geoserver_admin_settings_credentials_form",
      "edit"
    ],
    "access arguments" => ["administer geoserver"],
    "file" => "includes/geoserver.admin.inc",
  ];

  // Delete geoserver credentials.
  $items["admin/geoserver/settings/credentials/delete"] = [
    "title" => "Delete Credentials",
    "description" => "Delete an existing credentials.",
    "page callback" => "drupal_get_form",
    "page arguments" => [
      "geoserver_admin_settings_credentials_form",
      "delete"
    ],
    "access arguments" => ["administer geoserver"],
    "file" => "includes/geoserver.admin.inc",
  ];

  return $items;
}