<?php
/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function geoserver_help($path, $arg) {
  switch ($path) {
    case "admin/help#geoserver":
      return t("Displays links to nodes created on this date");
      break;
  }
}

function geoserver_menu() {
  $items = [];

  $items["admin/geoserver/settings"] = [
    "title" => "Geoserver Admin",
    "description" => "Provides a form so users can manage the settings",
    "page callback" => "geoserver_admin_list",
    "page arguments" => [],
    "access arguments" => ["use geoserver"],
    "file" => "includes/geoserver.admin.inc",
  ];
  return $items;
}